# Global settings (apply to all packages unless overridden)
filename: "mock_{{.InterfaceName}}.go"
dir: "mocks"
outpkg: "mocks"
with-expecter: true
packages:
  github.com/hyperledger/fabric-contract-api-go/v2/contractapi:
    interfaces:
      TransactionContextInterface:
  github.com/hyperledger/fabric-chaincode-go/v2/pkg/cid:
    interfaces:
      ClientIdentity:
  github.com/IceTweak/hyperacc:
    interfaces:
      Rule:
