// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hyperledger/fabric-contract-api-go/v2/contractapi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRule creates a new instance of MockRule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRule {
	mock := &MockRule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRule is an autogenerated mock type for the Rule type
type MockRule struct {
	mock.Mock
}

type MockRule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRule) EXPECT() *MockRule_Expecter {
	return &MockRule_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockRule
func (_mock *MockRule) Check(ctx contractapi.TransactionContextInterface) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(contractapi.TransactionContextInterface) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRule_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockRule_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx contractapi.TransactionContextInterface
func (_e *MockRule_Expecter) Check(ctx interface{}) *MockRule_Check_Call {
	return &MockRule_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *MockRule_Check_Call) Run(run func(ctx contractapi.TransactionContextInterface)) *MockRule_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 contractapi.TransactionContextInterface
		if args[0] != nil {
			arg0 = args[0].(contractapi.TransactionContextInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRule_Check_Call) Return(err error) *MockRule_Check_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRule_Check_Call) RunAndReturn(run func(ctx contractapi.TransactionContextInterface) error) *MockRule_Check_Call {
	_c.Call.Return(run)
	return _c
}
