// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hyperledger/fabric-chaincode-go/v2/pkg/cid"
	"github.com/hyperledger/fabric-chaincode-go/v2/shim"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionContextInterface creates a new instance of MockTransactionContextInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionContextInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionContextInterface {
	mock := &MockTransactionContextInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionContextInterface is an autogenerated mock type for the TransactionContextInterface type
type MockTransactionContextInterface struct {
	mock.Mock
}

type MockTransactionContextInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionContextInterface) EXPECT() *MockTransactionContextInterface_Expecter {
	return &MockTransactionContextInterface_Expecter{mock: &_m.Mock}
}

// GetClientIdentity provides a mock function for the type MockTransactionContextInterface
func (_mock *MockTransactionContextInterface) GetClientIdentity() cid.ClientIdentity {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientIdentity")
	}

	var r0 cid.ClientIdentity
	if returnFunc, ok := ret.Get(0).(func() cid.ClientIdentity); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cid.ClientIdentity)
		}
	}
	return r0
}

// MockTransactionContextInterface_GetClientIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientIdentity'
type MockTransactionContextInterface_GetClientIdentity_Call struct {
	*mock.Call
}

// GetClientIdentity is a helper method to define mock.On call
func (_e *MockTransactionContextInterface_Expecter) GetClientIdentity() *MockTransactionContextInterface_GetClientIdentity_Call {
	return &MockTransactionContextInterface_GetClientIdentity_Call{Call: _e.mock.On("GetClientIdentity")}
}

func (_c *MockTransactionContextInterface_GetClientIdentity_Call) Run(run func()) *MockTransactionContextInterface_GetClientIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionContextInterface_GetClientIdentity_Call) Return(clientIdentity cid.ClientIdentity) *MockTransactionContextInterface_GetClientIdentity_Call {
	_c.Call.Return(clientIdentity)
	return _c
}

func (_c *MockTransactionContextInterface_GetClientIdentity_Call) RunAndReturn(run func() cid.ClientIdentity) *MockTransactionContextInterface_GetClientIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// GetStub provides a mock function for the type MockTransactionContextInterface
func (_mock *MockTransactionContextInterface) GetStub() shim.ChaincodeStubInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStub")
	}

	var r0 shim.ChaincodeStubInterface
	if returnFunc, ok := ret.Get(0).(func() shim.ChaincodeStubInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.ChaincodeStubInterface)
		}
	}
	return r0
}

// MockTransactionContextInterface_GetStub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStub'
type MockTransactionContextInterface_GetStub_Call struct {
	*mock.Call
}

// GetStub is a helper method to define mock.On call
func (_e *MockTransactionContextInterface_Expecter) GetStub() *MockTransactionContextInterface_GetStub_Call {
	return &MockTransactionContextInterface_GetStub_Call{Call: _e.mock.On("GetStub")}
}

func (_c *MockTransactionContextInterface_GetStub_Call) Run(run func()) *MockTransactionContextInterface_GetStub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionContextInterface_GetStub_Call) Return(chaincodeStubInterface shim.ChaincodeStubInterface) *MockTransactionContextInterface_GetStub_Call {
	_c.Call.Return(chaincodeStubInterface)
	return _c
}

func (_c *MockTransactionContextInterface_GetStub_Call) RunAndReturn(run func() shim.ChaincodeStubInterface) *MockTransactionContextInterface_GetStub_Call {
	_c.Call.Return(run)
	return _c
}
